<?php

namespace makinuk\ICalendar;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-09 at 12:31:04.
 */
class ICalendarTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ICalendar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ICalendar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers makinuk\ICalendar\ICalendar::setMethod
     * @todo   Implement testSetMethod().
     */
    public function testSetMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers makinuk\ICalendar\ICalendar::addEvent
     * @todo   Implement testAddEvent().
     */
    public function testAddEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers makinuk\ICalendar\ICalendar::show
     * @todo   Implement testShow().
     */
    public function testShow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers makinuk\ICalendar\ICalendar::saveToFile
     */
    public function testSaveToFile() {
        $file = dirname(__FILE__) . DIRECTORY_SEPARATOR . "icalOut.ics";

        if (file_exists($file)) {
            unlink($file);
        }

        $event = new ICalEvent();
        $event->setUId(1234)
                ->setSummary("Summary")
                ->setOrganizer(new ICalPerson("Mustafa AKIN", "m.akin@makinuk.com"))
                ->setLocation("Istanbul")
                ->setEndDate(strtotime("+26 hours"))
                ->setStartDate(strtotime("+24 hours"))
                ->setDescription("Description");
        $this->object->addEvent($event);
        $this->object->saveToFile($file);

        $this->assertFileExists($file);
    }

    /**
     * @covers makinuk\ICalendar\ICalendar::getCalendarText
     * @todo   Implement testGetCalendarText().
     */
    public function testGetCalendarText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers makinuk\ICalendar\ICalendar::convertUTC
     * @todo   Implement testConvertUTC().
     */
    public function testConvertUTC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
